#!/usr/bin/env python3

import filetype
import logging
import os
import sys
import time
from PIL import Image as pilImage
from PIL import ImageTk

from tkinter import *
from tkinter import ttk
from tkinter import font
from tkinter import messagebox

import plorn_album
import plorn_config
from plorn_config import FONTSIZE
import plorn_db
import plorn_name
import plorn_photo
import plorn_place

#-- the application
class Plorn(Tk):
    def __init__(self):
        global config

        super().__init__()
        self.geometry("800x600")
        self.title("plorn")
        self.columnconfigure(0, weight=1)
        self.rowconfigure(0, weight=1)
        font.nametofont("TkDefaultFont").configure(size=FONTSIZE)
        self.db = plorn_db.open(config.get_dbname())

        #-- create these as placeholders
        self.albums_tab = 0
        self.aview = None
        self.album_list = []
        self.album_count = 0
        self.album_count_label = StringVar()
        self.current_album = None
        self.current_album_name = StringVar()
        self.album_label = StringVar()

        self.photos_tab = 1
        self.pview = None
        self.photo_list = []
        self.button_imgs = {}
        self.last_button_img = None
        self.photo_count = 0
        self.photo_count_label = StringVar()
        self.current_photo = None
        self.current_photo_button = None
        self.current_photo_name = StringVar()
        self.photo_label = StringVar()

        self.names_tab  = 2
        self.nview = None
        self.name_list = []
        self.last_name_id = None

        self.places_tab = 3
        self.lview = None
        self.place_list = []
        self.last_place_id = None

        self.settings_tab = 4

        #-- main frame for the application
        self.mainframe = ttk.Frame(self, padding="10 10 10 10")
        self.mainframe["borderwidth"] = 5
        self.mainframe["relief"] = "groove"
        self.mainframe.grid(column=0, row=0, sticky=(N, W, E, S))
        self.mainframe.columnconfigure(0, weight=1)
        self.mainframe.columnconfigure(1, weight=1)
        self.mainframe.columnconfigure(2, weight=1)
        self.mainframe.rowconfigure(0, weight=10)
        self.mainframe.rowconfigure(1, weight=1)
        self.mainframe.rowconfigure(2, weight=1)
        self.mainframe.rowconfigure(3, weight=30)
        self.mainframe.rowconfigure(4, weight=1)
        self.mainframe.rowconfigure(5, weight=1)
        self.mainframe.rowconfigure(6, weight=1)
        self.mainframe.rowconfigure(7, weight=10)

        label_text = "plorn: photo catalog"
        lheader = ttk.Label(self.mainframe, width=30,
                            text=f"{label_text:<30}")
        lheader.grid(column=0, row=0, sticky=(W))
        blanks = "      "
        mheader = ttk.Label(self.mainframe, width=30, text=f"{blanks:^30}")
        mheader.grid(column=1, row=0)
        value = f"version {plorn_config.version} "
        rheader = ttk.Label(self.mainframe, width=30, text=f"{value:>30}")
        rheader.grid(column=2, row=0, sticky=(E))
        sep1 = ttk.Separator(self.mainframe, orient=HORIZONTAL)
        sep1.grid(column=0, row=1, columnspan=3, sticky=(W+E))
        sep2 = ttk.Separator(self.mainframe, orient=HORIZONTAL)
        sep2.grid(column=0, row=2, columnspan=3, sticky=(W+E))

        #-- create a tabbed pane windows
        self.notebook = ttk.Notebook(self.mainframe)
        self.notebook.grid(column=0, row=3, columnspan=3, sticky=(N, W, E, S))

        #   ... that has an album list
        self.albums = ttk.Frame(self.notebook, padding="5 5 5 5")
        self.albums["borderwidth"] = 2
        self.albums["relief"] = "groove"
        self.album_buttons = []
        self.build_album_list(self.albums)
        self.notebook.add(self.albums, text=" Albums ")
        self.albums_tab = 0

        #   ... and that has a photo list for the current album
        self.photos = ttk.Frame(self.notebook, padding="5 5 5 5")
        self.photos["borderwidth"] = 2
        self.photos["relief"] = "groove"
        self.photo_buttons = []
        self.current_album = None
        self.build_photo_list(self.photos)
        self.notebook.add(self.photos, text=" Photos ")
        self.photos_tab = 1

        #   ... and there are all sorts of names to choose from
        self.names = ttk.Frame(self.notebook, padding="5 5 5 5")
        self.names["borderwidth"] = 2
        self.names["relief"] = "groove"
        self.current_photo = None
        self.build_name_list(self.names)
        self.notebook.add(self.names, text=" Names ")
        self.names_tab = 2

        #   ... and there are all sorts of places to choose from
        self.places = ttk.Frame(self.notebook, padding="5 5 5 5")
        self.places["borderwidth"] = 2
        self.places["relief"] = "groove"
        self.current_photo = None
        self.build_place_list(self.places)
        self.notebook.add(self.places, text=" Places ")
        self.places_tab = 3

        #   ... and that has a config table for the application
        self.settings = ttk.Frame(self.notebook, padding="5 5 5 5")
        self.settings["borderwidth"] = 2
        self.settings["relief"] = "groove"
        self.settings.columnconfigure(0, weight=1)
        self.settings.columnconfigure(1, weight=2)
        self.build_settings(self.settings)
        self.notebook.add(self.settings, text=" Settings ")
        self.settings_tab = 4

        #-- and some counts of albums and photos ....
        sep3 = ttk.Separator(self.mainframe, orient=HORIZONTAL)
        sep3.grid(column=0, row=4, columnspan=3, sticky=(W+E))

        self.album_count_label.set(f"Albums: {self.db.album_count()}")
        album_count_label = ttk.Label(self.mainframe, width=16,
                                      textvariable=self.album_count_label)
        album_count_label.grid(column=0, row=5, sticky=(W))

        self.photo_count_label.set(f"Photos: {self.db.photo_count()}")
        photo_count_label = ttk.Label(self.mainframe, width=16,
                                      textvariable=self.photo_count_label)
        photo_count_label.grid(column=1, row=5, sticky=(W))

        #-- and an exit button ....
        sep4 = ttk.Separator(self.mainframe, orient=HORIZONTAL)
        sep4.grid(column=0, row=6, columnspan=3, sticky=(W+E))
        b = ttk.Button(self.mainframe, text="Quit", command=self.destroy)
        b.grid(column=1, row=7)

    def update_albumview(self):
        for ii in self.aview.get_children():
            self.aview.delete(ii)
        self.album_list.clear()
        self.album_list = self.db.get_albums()
        self.album_list.sort(key=lambda x: x["name"])
        logger.debug(f"update to: {str(self.album_list)}")
        for ii in self.album_list:
            self.aview.insert("", END,
                              text=ii["id"],
                              values=(ii["name"], ii["path"],
                                      ii["photo_count"]))
        self.aview.focus_set()
        kids = self.aview.get_children()
        if len(kids) > 0:
            child_id = kids[0]
            if child_id != "":
                self.aview.focus(child_id)
                self.aview.selection_set(child_id)
                entry = self.aview.item(child_id)
                self.current_album = self.db.get_album_object(entry["text"])
                self.current_album_name.set(self.current_album.get_name())

        self.album_count_label.set(f"Albums: {self.db.album_count()}")
        self.photo_count_label.set(f"Photos: {self.db.photo_count()}")

    def get_symlink(self):
        linkname = os.path.join(config.get_datadir(),
                                f"album{self.current_album.get_id():04}")
        if not (os.path.exists(linkname) and os.path.islink(linkname)):
            fullpath = os.path.expanduser(self.current_album.get_path())
            actualdir = os.path.abspath(fullpath)
            logger.debug(f"symlink {linkname} to {actualdir}")
            os.symlink(actualdir, linkname, target_is_directory=True)
        return linkname

    def collect_images(self, linkname):
        photo_list = []
        entries = os.listdir(linkname)
        for ii in entries:
            fullpath = os.path.join(linkname, ii)
            logger.debug(f"checking file type of {fullpath}")
            if os.path.isfile(fullpath):
                if filetype.is_image(fullpath):
                    logger.debug(f"collected image {fullpath}")
                    photo_list.append(fullpath)
        return photo_list

    def add_album(self):
        logger.debug("adding album")
        addone = plorn_album.PlornAddAlbum(self, self.album_list)
        addone.grab_set()
        self.wait_window(addone)
        
        album_id = self.db.get_last_album_id()
        if album_id != None:
            row = self.db.get_album_by_id(album_id)
            self.current_album = plorn_album.PlornAlbum(row["name"],
                                        row["path"], id=row["id"],
                                        dated=row["dated"], notes=row["notes"])
            logger.debug(f"add photos to {self.current_album.get_name()}")
            linkname = self.get_symlink()
            photo_list = self.collect_images(linkname)
            album_id = self.current_album.get_id()
            self.photo_list.clear()
            self.button_imgs.clear()
            for ii in photo_list:
                name = os.path.basename(ii)
                photo = plorn_photo.PlornPhoto(name, ii, id=None,
                                               album_id=album_id)
                logger.debug(f"add photo {ii} with album_id {album_id}")
                id = self.db.add_photo(photo, album_id)
            for ii in self.db.get_photos(album_id):
                self.photo_list.append(ii)
            logger.debug(f"photo_list {str(self.photo_list)}")
            self.update_photoview(album_id)
            self.update_albumview()

    def remove_album(self):
        row = self.aview.focus()
        if row != "":
            album = self.aview.item(row)
            album_name = album["values"][0]
            logger.debug(f"remove album {album_name}")
            rmone = plorn_album.PlornRemoveAlbum(self, album_name,
                                                 self.album_list)
            rmone.grab_set()
            self.wait_window(rmone)
            self.update_albumview()
        else:
            messagebox.showerror(parent=self,
                                 title="Select an Album",
                                 detail="Please select an album to remove")

    def album_info(self):
        row = self.aview.focus()
        if row != "":
            album = self.aview.item(row)
            album_name = album["values"][0]
            logger.debug(f"show info for {album_name}")
            showone = plorn_album.PlornShowAlbum(self, album_name)
            showone.grab_set()
            self.wait_window(showone)
        else:
            messagebox.showerror(parent=self,
                                 title="Select an Album",
                                 detail="Please select an album to show")

    def up_photo(self, event):
        cur = self.last_button_img
        child = self.pview.prev(cur)
        if not child:
            child = cur
        logger.debug(f"up_photo selection: {str(cur)} -> {str(child)}")
        self.pview.selection_set(child)
        self.set_button_img(child)
        self.last_button_img = child

    def down_photo(self, event):
        cur = self.last_button_img
        child = self.pview.next(cur)
        if not child:
            child = cur
        logger.debug(f"down_photo selection: {str(cur)} -> {str(child)}")
        self.pview.selection_set(child)
        self.set_button_img(child)
        self.last_button_img = child

    def select_photo(self, event):
        child = self.pview.identify_row(event.y)
        if not child:
            child = self.last_button_img
        logger.debug(f"select_photo selection: {str(child)}")
        self.pview.selection_set(child)
        self.set_button_img(child)
        self.last_button_img = child

    def set_button_img(self, child):
        logger.debug(f"set_button_img entry: {str(child)}")
        if child != "":
            logger.debug(f"set_button_img: [{len(self.button_imgs)}] {str(child)}")
            self.current_photo_button.config(image=self.button_imgs[child])

    def update_photoview(self, album_id):
        if self.current_album == None:
            return

        self.current_album_name.set(self.current_album.get_name())
        context_msg = f"Album: {self.current_album_name.get()}"
        self.album_label.set(context_msg)

        for ii in self.pview.get_children():
            self.pview.delete(ii)
        self.photo_list.clear()
        self.photo_list = self.db.get_photos(album_id)
        self.photo_list.sort(key=lambda x: x["id"])
        self.button_imgs.clear()
        logger.debug(f"update to: {str(self.photo_list)}")
        for ii in self.photo_list:
            child = self.pview.insert("", END,
                                      text=ii["id"],
                                      values=(ii["name"], ii["path"]))
            raw_img = pilImage.open(ii["path"])
            thumbnail = raw_img.resize((100,100))
            button_img = ImageTk.PhotoImage(image=thumbnail)
            self.button_imgs[child] = button_img
            logger.debug(f"add btn img for child {child} from {ii["path"]}")

        self.pview.focus_set()
        kids = self.pview.get_children()
        if len(kids) > 0:
            child_id = self.pview.get_children()[0]
            self.last_button_img = child_id
            self.pview.selection_set(child_id)
            self.pview.focus(child_id)
            self.set_button_img(child_id)
            db_id = self.pview.item(child_id)["text"]
            self.current_photo = self.db.get_photo_object(db_id)
            self.photo_label.set(f"Photo: {self.current_photo.get_name()}")

    def got_called(self, event):
        logger.debug(f"got called for {str(event)}")

    def open_album(self):
        row = self.aview.focus()
        if row != "":
            album_info = self.aview.item(row)
            album_id = album_info["text"]
            album_name = album_info["values"][0]
            self.current_album = self.db.get_album_object(album_id)
            logger.debug(f"open album {album_name}")
            self.notebook.select(self.photos_tab)
            self.update_photoview(album_id)
        else:
            messagebox.showerror(parent=self,
                                 title="Select an Album",
                                 detail="Please select an album to open")

    def edit_album(self):
        row = self.aview.focus()
        if row != "":
            album = self.aview.item(row)
            album_name = album["values"][0]
            logger.debug(f"edit album {album_name}")
            showone = plorn_album.PlornEditAlbum(self,
                                                 album_name,
                                                 self.album_list)
            showone.grab_set()
            self.wait_window(showone)
            self.update_albumview()
        else:
            messagebox.showerror(parent=self,
                                 title="Select an Album",
                                 detail="Please select an album to edit")

    def build_album_list(self, parent):
        tfont = font.nametofont("TkDefaultFont")

        parent.columnconfigure(0, weight=8)
        parent.columnconfigure(1, weight=2)
        parent.rowconfigure(0, weight=1)
        parent.pack()

        lframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        lframe.grid(column=0, row=0)
        rframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        rframe.grid(column=1, row=0)

        style = ttk.Style()
        style.layout("plorn.Treeview",
            [("Treeview.field", {"sticky": "NWES", "border": 1, "children": [
                ("Treeview.padding", {"sticky": "NWES", "children": [
                    ("Treeview.treearea", {"sticky": "NWES"})
                    ]})
                ]})
            ])
        style.configure("plorn.Treeview",
                        font=("TkDefaultFont", FONTSIZE),
                        rowheight=30,
                       )
        style.configure("plorn.Treeview.Heading",
                        font=("TkDefaultFont", FONTSIZE))
        aview = ttk.Treeview(lframe,
                             columns=("name", "path", "photos"),
                             selectmode="browse",
                             style="plorn.Treeview")
        aview.column("#0", anchor="center", minwidth=0, width=100)
        aview.heading("#0", text="ID")
        aview.column("name", anchor="w", minwidth=0, width=200)
        aview.heading("name", text="Name")
        aview.column("path", anchor="w", minwidth=0, width=200)
        aview.heading("path", text="Path")
        aview.column("photos", anchor="center", minwidth=0, width=100)
        aview.heading("photos", text="Photos")
        aview.grid(column=0, row=0)
        xscrollbar = ttk.Scrollbar(lframe, orient="vertical",
                                  command=aview.yview)
        xscrollbar.grid(column=1, row=0)
        aview.configure(xscrollcommand=xscrollbar.set)
        yscrollbar = ttk.Scrollbar(lframe, orient="horizontal",
                                  command=aview.xview)
        yscrollbar.grid(column=0, row=1)
        aview.configure(yscrollcommand=yscrollbar.set)
        self.aview = aview
        self.update_albumview()

        self.album_buttons = [
            ttk.Button(rframe, text="open", command=self.open_album),
            ttk.Button(rframe, text="view", command=self.album_info),
            ttk.Button(rframe, text="add", command=self.add_album),
            ttk.Button(rframe, text="remove", command=self.remove_album),
            ttk.Button(rframe, text="edit", command=self.edit_album),
        ]
        for n in range(0, len(self.album_buttons)):
            self.album_buttons[n].grid(column=0, row=n)

    def build_photo_list(self, parent):
        tfont = font.nametofont("TkDefaultFont")

        parent.columnconfigure(0, weight=8)
        parent.columnconfigure(1, weight=2)
        parent.rowconfigure(0, weight=1)
        parent.pack()

        context_msg = "Album: <none>"
        if self.current_album != None:
            self.current_album_name.set(self.current_album.get_name())
            context_msg = f"Album: {self.current_album_name.get()}"
        self.album_label.set(context_msg)
        album_label = ttk.Label(parent, width=40,
                                textvariable=self.album_label)
        album_label.grid(column=0, row=0, sticky=(W))

        lframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        lframe.grid(column=0, row=1)
        rframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        rframe.grid(column=1, row=1)

        style = ttk.Style()
        style.layout("plorn.Treeview",
            [("Treeview.field", {"sticky": "NWES", "border": 1, "children": [
                ("Treeview.padding", {"sticky": "NWES", "children": [
                    ("Treeview.treearea", {"sticky": "NWES"})
                    ]})
                ]})
            ])
        style.configure("plorn.Treeview",
                        font=("TkDefaultFont", FONTSIZE),
                        rowheight=30,
                       )
        style.configure("plorn.Treeview.Heading",
                        font=("TkDefaultFont", FONTSIZE))
        pview = ttk.Treeview(lframe,
                             columns=("name", "path", "photos"),
                             selectmode="browse",
                             style="plorn.Treeview")
        pview.column("#0", anchor="center", minwidth=0, width=100)
        pview.heading("#0", text="ID")
        pview.column("name", anchor="w", minwidth=0, width=200)
        pview.heading("name", text="Name")
        pview.column("path", anchor="w", minwidth=0, width=200)
        pview.heading("path", text="Path")
        pview.grid(column=0, row=0)
        xscrollbar = ttk.Scrollbar(lframe, orient="vertical",
                                  command=pview.yview)
        xscrollbar.grid(column=1, row=0)
        pview.configure(xscrollcommand=xscrollbar.set)
        yscrollbar = ttk.Scrollbar(lframe, orient="horizontal",
                                  command=pview.xview)
        yscrollbar.grid(column=0, row=1)
        pview.configure(yscrollcommand=yscrollbar.set)
        pview.bind("<Up>", self.up_photo)
        pview.bind("<Down>", self.down_photo)
        pview.bind("<ButtonRelease-1>", self.select_photo)
        self.pview = pview

        self.current_photo_button = ttk.Button(rframe,
                                        state="readonly",
                                        compound="image")
        self.current_photo_button.grid(column=0, row=0)

        self.photo_buttons = [
            ttk.Button(rframe, text="view", command=self.photo_info),
            ttk.Button(rframe, text="add", command=self.add_photo),
            ttk.Button(rframe, text="remove", command=self.remove_photo),
            ttk.Button(rframe, text="edit", command=self.edit_photo),
        ]
        for n in range(0, len(self.photo_buttons)):
            self.photo_buttons[n].grid(column=0, row=n+1)

    def photo_info(self):
        row = self.pview.focus()
        if row != "":
            photo = self.pview.item(row)
            photo_id = photo["text"]
            logger.debug(f"show info for {photo_id}")
            showone = plorn_photo.PlornShowPhoto(self, photo_id)
            showone.grab_set()
            self.wait_window(showone)
        else:
            messagebox.showerror(parent=self,
                                 title="Select a Photo",
                                 detail="Please select a photo to show")

    def remove_photo(self):
        row = self.pview.focus()
        if row != "":
            photo_entry = self.pview.item(row)
            photo_id = photo_entry["text"]
            photo = self.db.get_photo_by_id(photo_id)
            logger.debug(f"remove_photo: row {row}, id {photo_id}, photo {str(photo)}")
            rmone = plorn_photo.PlornRemovePhoto(self, photo_id,
                                                 self.photo_list)
            rmone.grab_set()
            self.wait_window(rmone)
            del self.button_imgs[row]
            album = self.db.get_album_object(photo["album_id"])
            self.update_photoview(album.get_id())
            self.update_albumview()
        else:
            messagebox.showerror(parent=self,
                                 title="Select a Photo",
                                 detail="Please select a photo to remove")

    def edit_photo(self):
        row = self.pview.focus()
        if row != "":
            photo_entry = self.pview.item(row)
            photo_id = photo_entry["text"]
            photo = self.db.get_photo_by_id(photo_id)
            logger.debug(f"edit_photo: row {row}, id {photo_id}, photo {str(photo)}")
            rmone = plorn_photo.PlornEditPhoto(self, photo_id)
            rmone.grab_set()
            self.wait_window(rmone)
            album = self.db.get_album_object(photo["album_id"])
            self.update_photoview(album.get_id())
            self.update_albumview()
        else:
            messagebox.showerror(parent=self,
                                 title="Select a Photo",
                                 detail="Please select a photo to edit")

    def add_photo(self):
        logger.debug("adding photo")
        album_id = self.current_album.get_id()
        addone = plorn_photo.PlornAddPhoto(self, album_id)
        addone.grab_set()
        self.wait_window(addone)
        
        photo_id = self.db.get_last_photo_id()
        if photo_id != None:
            photo = self.db.get_photo_object(photo_id)
            logger.debug(f"add a photo to {self.current_album.get_name()}")
            linkname = self.get_symlink()
            self.photo_list.clear()
            self.button_imgs.clear()
            logger.debug(f"add photo {photo.get_name()} with album_id {album_id}")
            id = self.db.add_photo(photo, album_id)
            for ii in self.db.get_photos(album_id):
                self.photo_list.append(ii)
            self.update_photoview(album_id)
            self.update_albumview()

    def up_name(self, event):
        cur = self.last_name_id
        child = self.nview.prev(cur)
        if not child:
            child = cur
        logger.debug(f"up_name selection: {str(cur)} -> {str(child)}")
        self.nview.selection_set(child)
        self.last_name_id = child

    def down_name(self, event):
        cur = self.last_name_id
        child = self.nview.next(cur)
        if not child:
            child = cur
        logger.debug(f"down_name selection: {str(cur)} -> {str(child)}")
        self.nview.selection_set(child)
        self.last_name_id = child

    def select_name(self, event):
        child = self.nview.identify_row(event.y)
        if not child:
            child = self.last_name_id
        logger.debug(f"select_name selection: {str(child)}")
        self.nview.selection_set(child)
        self.last_name_id = child

    def deselect_name(self, event):
        self.nview.selection_clear()
        self.last_name_id = None

    def update_nameview(self):
        for ii in self.nview.get_children():
            self.nview.delete(ii)
        self.name_list.clear()
        self.name_list = self.db.get_names()
        self.name_list.sort(key=lambda x: x["name"])
        logger.debug(f"update to: {str(self.name_list)}")
        tree_ids = {}
        while len(tree_ids) < len(self.name_list):
            for ii in self.name_list:
                #logger.debug(f"insert: {str(ii)}")
                id = ii["id"]
                pid = ii["parent_id"]
                name = ii["name"]
                under_id = ""
                if pid == 0 and id not in tree_ids:
                    curid = self.nview.insert(under_id, END,
                                              text=ii["name"],
                                              values=(id, pid)
                                              )
                    tree_ids[id] = curid
                elif pid != 0 and id not in tree_ids:
                    if pid in tree_ids:
                        under_id = tree_ids[pid]
                        curid = self.nview.insert(under_id, END,
                                                  text=ii["name"],
                                                  values=(id, pid)
                                                  )
                        tree_ids[id] = curid

            #logger.debug(f"tree {len(tree_ids)}, names {len(self.name_list)}")

    def add_family(self):
        logger.debug(f"adding family")
        addone = plorn_name.PlornAddName(self, parent_id=0)
        addone.grab_set()
        self.wait_window(addone)
        
        name_id, parent_id = self.db.get_last_name_id()
        if name_id != None:
            name = self.db.get_name_object(name_id, parent_id)
            logger.debug(f"add family {name.get_name()}")
            self.update_nameview()

    def add_person(self):
        parent = self.nview.focus()
        entry = self.nview.item(parent)
        if parent == "":
            parent_id = 1           # default to <unknown>
        else:
            parent_id = entry["values"][1]
        logger.debug(f"adding person under {str(entry)}")
        addone = plorn_name.PlornAddName(self, parent_id=parent_id)
        addone.grab_set()
        self.wait_window(addone)
        
        name_id, parent_id = self.db.get_last_name_id()
        if name_id != None:
            name = self.db.get_name_object(name_id, parent_id)
            logger.debug(f"added person {name.get_name()}")
            self.update_nameview()

    def remove_name(self):
        entry_id = self.nview.focus()
        if entry_id == "":
            messagebox.showerror(parent=self,
                                 title="Remove Name",
                                 detail="Please select a name to remove")
            return
        entry = self.nview.item(entry_id)
        logger.debug(f"entry: {str(entry)}")
        e_id = entry["values"][0]
        e_pid = entry["values"][1]
        name = self.db.get_name_object(e_id, parent_id=e_pid)
        name_id = name.get_id()
        parent_id = name.get_parent_id()
        logger.debug(f"removing name {name.get_name()} from {parent_id}")
        rmone = plorn_name.PlornRemoveName(self, name_id, parent_id)
        rmone.grab_set()
        self.wait_window(rmone)
        self.update_nameview()

    def edit_name(self):
        entry = self.nview.focus()
        if entry != "":
            name_entry = self.nview.item(entry)
            name = name_entry["text"]
            name_id = name_entry["values"][0]
            parent_id = name_entry["values"][1]
            logger.debug(f"edit name {str(entry)}")
            showone = plorn_name.PlornEditName(self, name, name_id,
                                               parent_id=parent_id)
            showone.grab_set()
            self.wait_window(showone)
            self.update_nameview()
        else:
            messagebox.showerror(parent=self,
                                 title="Select a Name",
                                 detail="Please select a name to edit")

    def build_name_list(self, parent):
        tfont = font.nametofont("TkDefaultFont")

        parent.columnconfigure(0, weight=8)
        parent.columnconfigure(1, weight=2)
        parent.rowconfigure(0, weight=1)
        parent.pack()

        lframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        lframe.grid(column=0, row=0)
        rframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        rframe.grid(column=1, row=0)

        style = ttk.Style()
        style.layout("plorn.Treeview",
            [("Treeview.field", {"sticky": "NWES", "border": 1, "children": [
                ("Treeview.padding", {"sticky": "NWES", "children": [
                    ("Treeview.treearea", {"sticky": "NWES"})
                    ]})
                ]})
            ])
        style.configure("plorn.Treeview",
                        font=("TkDefaultFont", FONTSIZE),
                        rowheight=30,
                       )
        style.configure("plorn.Treeview.Heading",
                        font=("TkDefaultFont", FONTSIZE))
        nview = ttk.Treeview(lframe,
                             columns=("id", "parent"),
                             selectmode="browse",
                             style="plorn.Treeview")
        nview.column("#0", anchor="w", minwidth=0, width=500)
        nview.heading("#0", text="Name")
        nview.column("id", anchor="w", minwidth=0, width=100)
        nview.heading("id", text="ID")
        nview.column("parent", anchor="w", minwidth=0, width=100)
        nview.heading("parent", text="Parent")
        nview["displaycolumns"] = ()
        nview.grid(column=0, row=0)
        xscrollbar = ttk.Scrollbar(lframe, orient="vertical",
                                  command=nview.yview)
        xscrollbar.grid(column=1, row=0)
        nview.configure(xscrollcommand=xscrollbar.set)
        yscrollbar = ttk.Scrollbar(lframe, orient="horizontal",
                                  command=nview.xview)
        yscrollbar.grid(column=0, row=1)
        nview.configure(yscrollcommand=yscrollbar.set)
        nview.bind("<Up>", self.up_name)
        nview.bind("<Down>", self.down_name)
        nview.bind("<ButtonRelease-1>", self.select_name)
        nview.bind("<Double-Button-1>", self.deselect_name)
        self.nview = nview

        self.name_buttons = [
            ttk.Button(rframe, text="add family", command=self.add_family),
            ttk.Button(rframe, text="add person", command=self.add_person),
            ttk.Button(rframe, text="remove", command=self.remove_name),
            ttk.Button(rframe, text="edit", command=self.edit_name),
        ]
        for n in range(0, len(self.name_buttons)):
            self.name_buttons[n].grid(column=0, row=n+1)
        self.update_nameview()

    def up_place(self, event):
        cur = self.last_place_id
        child = self.lview.prev(cur)
        if not child:
            child = cur
        logger.debug(f"up_place selection: {str(cur)} -> {str(child)}")
        self.lview.selection_set(child)
        self.last_place_id = child

    def down_place(self, event):
        cur = self.last_place_id
        child = self.lview.next(cur)
        if not child:
            child = cur
        logger.debug(f"down_place selection: {str(cur)} -> {str(child)}")
        self.lview.selection_set(child)
        self.last_place_id = child

    def select_place(self, event):
        child = self.lview.identify_row(event.y)
        if not child:
            child = self.last_place_id
        logger.debug(f"select_place selection: {str(child)}")
        self.lview.selection_set(child)
        self.last_place_id = child

    def build_place_list(self, parent):
        tfont = font.nametofont("TkDefaultFont")

        parent.columnconfigure(0, weight=8)
        parent.columnconfigure(1, weight=2)
        parent.rowconfigure(0, weight=1)
        parent.pack()

        lframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        lframe.grid(column=0, row=0)
        rframe = ttk.Frame(parent, padding=(5, 5, 5, 5))
        rframe.grid(column=1, row=0)

        style = ttk.Style()
        style.layout("plorn.Treeview",
            [("Treeview.field", {"sticky": "NWES", "border": 1, "children": [
                ("Treeview.padding", {"sticky": "NWES", "children": [
                    ("Treeview.treearea", {"sticky": "NWES"})
                    ]})
                ]})
            ])
        style.configure("plorn.Treeview",
                        font=("TkDefaultFont", FONTSIZE),
                        rowheight=30,
                       )
        style.configure("plorn.Treeview.Heading",
                        font=("TkDefaultFont", FONTSIZE))
        lview = ttk.Treeview(lframe,
                             columns=("id", "parent"),
                             selectmode="browse",
                             style="plorn.Treeview")
        lview.column("#0", anchor="w", minwidth=0, width=500)
        lview.heading("#0", text="Place")
        lview.column("id", anchor="w", minwidth=0, width=100)
        lview.heading("id", text="ID")
        lview.column("parent", anchor="w", minwidth=0, width=100)
        lview.heading("parent", text="Parent")
        lview["displaycolumns"] = ()
        lview.grid(column=0, row=0)
        xscrollbar = ttk.Scrollbar(lframe, orient="vertical",
                                  command=lview.yview)
        xscrollbar.grid(column=1, row=0)
        lview.configure(xscrollcommand=xscrollbar.set)
        yscrollbar = ttk.Scrollbar(lframe, orient="horizontal",
                                  command=lview.xview)
        yscrollbar.grid(column=0, row=1)
        lview.configure(yscrollcommand=yscrollbar.set)
        lview.bind("<Up>", self.up_place)
        lview.bind("<Down>", self.down_place)
        lview.bind("<ButtonRelease-1>", self.select_place)
        self.lview = lview

        self.place_buttons = [
            ttk.Button(rframe, text="add", command=self.add_place),
            ttk.Button(rframe, text="remove", command=self.destroy),
            ttk.Button(rframe, text="edit", command=self.destroy),
        ]
        for n in range(0, len(self.place_buttons)):
            self.place_buttons[n].grid(column=0, row=n+1)
        self.update_placeview()

    def update_placeview(self):
        for ii in self.lview.get_children():
            self.lview.delete(ii)
        self.place_list.clear()
        self.place_list = self.db.get_places()
        self.place_list.sort(key=lambda x: x["place"])
        logger.debug(f"update to: {str(self.place_list)}")
        tree_ids = {}
        while len(tree_ids) < len(self.place_list):
            for ii in self.place_list:
                #logger.debug(f"insert: {str(ii)}")
                id = ii["id"]
                pid = ii["parent_id"]
                place = ii["place"]
                under_id = ""
                if pid == 0 and id not in tree_ids:
                    curid = self.lview.insert(under_id, END,
                                              text=ii["place"],
                                              values=(id, pid)
                                              )
                    tree_ids[id] = curid
                elif pid != 0 and id not in tree_ids:
                    if pid in tree_ids:
                        under_id = tree_ids[pid]
                        curid = self.lview.insert(under_id, END,
                                                  text=ii["place"],
                                                  values=(id, pid)
                                                  )
                        tree_ids[id] = curid

            #logger.debug(f"tree {len(tree_ids)}, places {len(self.place_list)}")

    def add_place(self):
        logger.debug(f"adding place")
        parent = self.lview.focus()
        if parent == "":
            pid = 0
        else:
            entry = self.lview.item(parent)
            pid = entry["values"][1]
        addone = plorn_place.PlornAddPlace(self, parent_id=pid)
        addone.grab_set()
        self.wait_window(addone)
        
        place_id, parent_id = self.db.get_last_place_id()
        if place_id != None:
            place = self.db.get_place_object(place_id, parent_id)
            logger.debug(f"add place {place.get_place()}")
            self.update_placeview()

    def build_settings(self, parent):
        config = plorn_config.get_config()
        tfont = font.nametofont("TkDefaultFont")

        items = [
            ["User Name:",        0, config.get_username()],
            ["Full Name:",        1, config.get_fullname()],
            ["Config Directory:", 2, config.get_configdir()],
            ["Data Directory:",   3, config.get_datadir()],
            ["SQLite Database:",  4, config.get_dbname()],
        ]

        num = 0
        labels = {}
        entries = {}
        for label_text, row, value in items:
            labels[row] = ttk.Label(parent, width=20, text=label_text)
            labels[row].grid(column=0, row=row)
            entries[row] = ttk.Entry(parent, width=30, font=tfont)
            entries[row].insert(0, value)
            entries[row].grid(column=1, row=row)
            entries[row].configure(state="readonly")


#-- set up logging
root_logger = logging.getLogger("")
root_logger.setLevel(logging.DEBUG)
fh = logging.FileHandler("plorn.log")
fh.setLevel(logging.DEBUG)
fhformat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
formatter = logging.Formatter(fhformat)
fh.setFormatter(formatter)
root_logger.addHandler(fh)

logger = logging.getLogger("plorn")
logger.setLevel(logging.DEBUG)

#-- get the config file
logger.debug("calling PlornConfig()")
config_name = None
if len(sys.argv) > 1:
    config = plorn_config.get_config(config_name)
else:
    config = plorn_config.get_config()

if __name__ == "__main__":
    plorn = Plorn()
    plorn.mainloop()

