#######################################################################
# Copyright (c) 2025, Albert H. Stone, III <ahs3@ahs3.net>
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Albert H. Stone, III <ahs3@ahs3.net>
#######################################################################
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "plorn"
dynamic = ["version"]
authors = [
	{ name="Al Stone", email="ahs3@ahs3.net" },
]
description = "Build catalogs of albums and photos"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = [ "COPYING", "COPYRIGHT", "LICENSES", ]
dependencies = [
	"filetype",
	"pillow",
]

[project.scripts]
plorn = "plorn.gui:user_interface"

[project.urls]
Homepage = "https://github.com/ahs3/plorn"
Documentation = "https://github.com/ahs3/plorn/README.md"
Repository = "https://github.com/ahs3/plorn.git"
Issues = "https://github.com/ahs3/plorn/issues"

[tool.pdm.version]
source = "file"
path = "src/plorn/config.py"

