#######################################################################
# Copyright (c) 2026, Albert H. Stone, III <ahs3@ahs3.net>
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Albert H. Stone, III <ahs3@ahs3.net>
#######################################################################
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "plorn"
dynamic = ["version"]
authors = [{ name="Al Stone", email="ahs3@ahs3.net" }]
description = "Build catalogs of albums and photos"
readme = "README.md"
requires-python = ">=3.14"
license = "GPL-3.0-or-later AND CC-BY-4.0"
license-files = [ "COPYING", "LICENSES", ]
dependencies = [ "pillow", "pyqt6", ]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["GUI", "Genealogy", "Photos", "Albums"]

[project.optional-dependencies]
dev = [ "pytest", "pytest-qt", ]

[project.scripts]
plorn = "plorn.__main__:main"

[project.urls]
Homepage = "https://codeberg.org/ahs3/plorn"
Documentation = "https://codeberg.org/ahs3/plorn/README.md"
Repository = "https://codeberg.org/ahs3/plorn.git"
Issues = "https://codeberg.org/ahs3/plorn/issues"

[tool.setuptools.dynamic]
version = {attr = "plorn.config.__version__"}

[tool.setuptools.package-data]
plorn = ["plorn_app.png"]

